workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Build APK with bypass
        script: | 
          flutter build apk --release --android-skip-build-dependency-validation
          flutter build appbundle --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk