workflows:
  android-workflow:
    name: Yuopni Android
    instance_type: linux_x2  # YE SASTA HAI - $0.045/min ~ ₹4/min
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

  ios-workflow:
    name: Yuopni iOS
    instance_type: mac_mini_m2  # YE MEHENGA HAI - $0.095/min ~ ₹8/min par iOS ke liye zaruri
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios && pod install
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa